name: CI/CD pipeline for automated deployment of DAGs into Composer
on: push
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Get code from repository
              uses: actions/checkout@v3
            
            - name: Authorize Google Cloud Platform
              uses: google-github-actions/auth@v1
              with:
                workload_identity_provider: principalSet://iam.googleapis.com/projects/131949951730/locations/global/workloadIdentityPools/github-actions-gcs/*
                service_account: gcs-service-account@burner-kunwadhw2.iam.gserviceaccount.com
            
            - name: Upload DAGs to Composer
              uses: 'google-github-actions/upload-cloud-storage@v1'
              with:
                  path: 'a/'
                  destination: 'kunal-bucket'
              
